name: Trigger Tata Workflow

on:
  push:
    branches:
      - main  # You can specify the branches you want this action to trigger on
  workflow_dispatch:
    inputs:
      param1:
        description: 'A parameter for the workflow'
        required: true
        default: 'value from toto'
jobs:
  trigger-tata:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Tata Workflow
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
            https://api.github.com/repos/ltroussellier/test_receive/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main","inputs":{"param1":"value from toto"}}'
